/*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
#include <stdio.h>
#include <string.h>
#include "mathhelp.h"
int main()
{
	int a = 0;
	int counter = 1;
	int stored = 0;
	while (a == 0)
	{
		int tri = 0;
		int i;
		for (i = 1; i <= counter; i++)
		{
			tri += i;
		}
		int result = factors(tri);
		if (result > stored)
		{
			printf("%d\n", result);
			stored = result;
		}
		if (result > 500)
		{
			printf ("%d", tri);
			printf ("%d", counter);
			break;
		}
		counter += 1;
		
	}
	
}